#include <Player.hpp>

#ifndef KEX_LOCALPLAYER_HPP
#define KEX_LOCALPLAYER_HPP


class AbstractScene {public:};
class BaseScreen : public AbstractScene {public:};
class UIScene : public BaseScreen {public:};
class SceneStack {
    public:
    void pushScreen(std::__ndk1::shared_ptr<AbstractScene>, bool);
};
class SceneFactory {
    public:
    std::__ndk1::shared_ptr<UIScene> createSignScreen(const BlockPos&);  
};

class LocalPlayer : public Player {
    public:
    class RegionListener;
    // virtual void initializeComponents(Actor::InitializationMethod, const VariantParameterList&);
    // virtual void setPos(const Vec3&);
    // virtual void move(const Vec3&);
    // virtual void teleportTo(const Vec3&, bool, int, int, const ActorUniqueID&);
    // virtual void normalTick();
    // virtual void startRiding(Actor&);
    // virtual void setSneaking(bool);
    // virtual bool isLocalPlayer() const;
    // virtual void actuallyHurt(int, const ActorDamageSource&, bool);
    // virtual void handleEntityEvent(ActorEvent, int);
    // virtual void setArmor(ArmorSlot, const ItemStack&);
    // virtual void setOffhandSlot(const ItemStack&);
    // virtual void handleInsidePortal(const BlockPos&);
    // virtual void changeDimension(AutomaticID<Dimension, int>, bool);
    // virtual void changeDimension(const ChangeDimensionPacket&);
    // virtual void* getControllingPlayer() const;
    // virtual void checkFallDamage(float, bool);
    // virtual void causeFallDamage(float);
    // virtual void playSynchronizedSound(LevelSoundEvent, const Vec3&, const Block&, bool);
    // virtual void playSynchronizedSound(LevelSoundEvent, const Vec3&, int, bool);
    // virtual void stopRiding(bool, bool, bool);
    // virtual void onEffectRemoved(MobEffectInstance&);
    // virtual void swing();
    // virtual void startSpinAttack();
    // virtual void stopSpinAttack();
    // virtual void die(const ActorDamageSource&);
    // virtual void* createMovementProxy();
    // virtual void _hurt(const ActorDamageSource&, int, bool, bool);
    // virtual void readAdditionalSaveData(const CompoundTag&, DataLoadHelper&);
    // virtual void addAdditionalSaveData(CompoundTag&);
    // virtual void _doAutoAttackOnTouch(Actor&);
    // virtual void setSprinting(bool);
    // virtual void travel(float, float, float);
    // virtual void applyFinalFriction(float, bool);
    // virtual void aiStep();
    // virtual void setItemSlot(EquipmentSlot, const ItemStack&);
    // virtual void jumpFromGround();
    // virtual void updateAi();
    // virtual bool _allowAscendingScaffolding() const;
    // virtual void prepareRegion(ChunkSource&);
    // virtual void destroyRegion();
    // virtual void suspendRegion();
    // virtual void _fireDimensionChanged();
    // virtual void tickWorld(const Tick&);
    // virtual void frameUpdate(FrameUpdateContextBase&);
    // virtual void* getTickingOffsets() const;
    // virtual void checkMovementStats(const Vec3&);
    // virtual void* getCurrentStructureFeature() const;
    // virtual bool isAutoJumpEnabled() const;
    // virtual void respawn();
    // virtual void resetRot();
    // virtual void resetPos(bool);
    // virtual bool isInTrialMode();
    // virtual void openPortfolio();
    // virtual void openBook(int, bool, int, BlockActor*);
    // virtual void openTrading(const ActorUniqueID&, bool);
    // virtual void openChalkboard(ChalkboardBlockActor&, bool);
    // virtual void openNpcInteractScreen(Actor&);
    // virtual void openInventory();
    // virtual void displayClientMessage(const std::__ndk1::string&);
    // virtual void displayTextObjectMessage(const TextObjectRoot&);
    // virtual void displayWhisperMessage(const std::__ndk1::string&, const std::__ndk1::string&, const std::__ndk1::string&, const std::__ndk1::string&);
    // virtual void startSleepInBed(const BlockPos&);
    // virtual void stopSleepInBed(bool, bool);
    // virtual bool canStartSleepInBed();
    // virtual void openSign(const BlockPos&);
    // virtual void playEmote(const std::__ndk1::string&);
    // virtual bool isHostingPlayer() const;
    // virtual bool isLoading() const;
    // virtual bool stopLoading();
    // virtual void setPlayerGameType(GameType);
    // virtual void _crit(Actor&);
    // virtual void* getEventing() const;
    // virtual void* getUserId() const;
    // virtual void addExperience(int);
    // virtual void addLevels(int);
    // virtual void deleteContainerManager();
    // virtual bool isEntityRelevant(const Actor&);
    // virtual bool isTeacher() const;
    // virtual void* sendInventoryTransaction(const InventoryTransaction&) const;
    // virtual void sendComplexInventoryTransaction(std::__ndk1::unique_ptr<ComplexInventoryTransaction>) const;
    // virtual void sendNetworkPacket(Packet&) const;
    // virtual PlayerEventCoordinator* getPlayerEventCoordinator();
    // virtual MoveInputHandler& getMoveInputHandler();
    // virtual InputMode getInputMode();
    // virtual int getPlayMode() const;
    bool hasBossRegistered(ActorUniqueID) const;
    void* getItemStackNetManagerClient() const;
    void registerFramewiseActionOrStop();
    float getOPortalEffectTime() const;
    float getPreloadingProgress();
    void setOPortalEffectTime(float);
    NetworkChunkSubscriber* getNetworkChunkSubscriber();
    void setAutoJumpEnabled(bool);
    void stopPaddling(Side);
    void setTeacher();
    unsigned int getViewBlockRadius() const;
    void setEmotePlayedEndedEarly(bool);
    void _computeBowOverride(Vec3&);
    /*unsigned?*/ int getPickRange() const;
    void removeRegionListener(RegionListener*);
    void clearMovementState();
    void setPortalEffectTime(float);
    void chat(const std::__ndk1::string&);
    void setInventoryOptions(const InventoryOptions&);
    void* _getClientPlayerEventCoordinator();
    void localPlayerTurn(const Vec2&);
    void* getLookBob() const;
    void _modifyDeltaByHMDPosition(Vec3&, float);
    bool isAbleToRespawn() const;
    void pickBlock(const HitResult&, bool);
    void* getItemStackNetManagerClient();
    float getPortalEffectTime() const;
    void* getOldLookBob() const;
    void frameUpdate(FrameUpdateContext&);
    void localPlayerRenderFrequencyMove(float);
    void _postJumpFrameOfReferenceAdjustCheck(bool);
    bool _shouldRotateWithCamera() const;
    void closeScreen();
    void setClientRespawnPotentialPosition(const Vec3&);
    Vec3* getClientRespawnPotentialPosition();
    void setJumpRidingScale(float);
    void sendInput();
    NetworkChunkSubscriber* getNetworkChunkSubscriber() const;
    void displayItemActivation(const ItemStack&);
    void _RotationVec2Modulus(Vec2&);
    void sendPosition();
    void setPlayerGameTypeWithoutServerNotification(GameType);
    void _calculateFlight(float, float, float);
    void markUIAnimationComponentDirty();
    void* getLoadingState() const;
    ClientInstance* getClientInstance() const;
    void _applyTurnDelta(const Vec2&);
    void requestChunkRadius(unsigned int);
    void updateAfterCamera(const Camera&);
    bool isFlying() const;
    void _fillChunksNeededForLoadOffsets();
    float getFieldOfViewModifier();
    void openCodeScreen();
    ItemStack* getActivatedItem() const;
    void handleArmorDamage(ArmorSlot, short);
    InventoryMenu* getInventoryMenu();
    void updateBeforeCamera(const Camera&, float);
    void initializeItemStackNetManager(bool);
    void resetLastHmdAngle();
    float getJumpRidingScale();
    void setLeavingLevel(bool);
    void sendEmotes();
    void startPaddling(Side);
    void setAllEmoteTelemetryData(const std::__ndk1::string&, int);
    InventoryOptions* getInventoryOptions() const;
    bool _hasLoadedEnoughChunksToView() const;
    void addRegionListener(RegionListener*);
    void fireEventPersonaEmotePlayed();
    void hurtTo(int);
    bool isLocalSplitscreenWith(const ActorUniqueID&) const;
    int getItemActivationOffsetX() const;
    int getItemActivationOffsetY() const;
    void setClientRespawnState(const PlayerRespawnState&);
    void* _getCrashDumpLogCategory();
    int getItemActivationTicks() const;
};


#endif //KEX_LOCALPLAYER_HPP