#include <Mob.hpp>

#ifndef KEX_PLAYER_HPP
#define KEX_PLAYER_HPP


class Agent;
class AnimationComponent;
class Attribute {public:};
class AttributeBuff { public: };
class InstantaneousAttributeBuff : public AttributeBuff {
    public:
    char filler[48];
    InstantaneousAttributeBuff(float, AttributeBuffType);
};
class AttributeInstance {
    public:
    float getCurrentValue() const;
    void setMaxValue(float);
    void addBuff(AttributeBuff const&);
};
class BlockActor;
class Camera;
class ChalkboardBlockActor;
class ChangeDimensionPacket;
class ChunkSource;
class ClientInstance;
class ClientPlayMode;
class ComplexInventoryTransaction;
class Container;
class EventPacket;
class FrameUpdateContext;
class FrameUpdateContextBase;
class HitResult;
class HudContainerManagerModel;
class InventoryMenu;
class InventoryOptions;
class InventoryTransaction;
#ifndef KEX_ITEM_HPP
    class Item;
#endif
class ItemDescriptor;
class ItemGroup;
class ItemStackBase;
#ifndef KEX_MOVEINPUTHANDLER_HPP
    class MoveInputHandler;
#endif
class NetworkChunkSubscriber;
class Packet;
class PacketObserver;
class PlayerEventCoordinator;
class PlayerInventory;
class PlayerListener;
class PlayerRespawnState;
class ResolvedTextObject;
class SerializedSkin;
class ServerMoveInputHandler;
class ServerPlayerEventCoordinator;
class ShieldItem;
class TextObjectRoot;
class Tick;

class Player : public Mob {
    public:
    static Attribute HUNGER;
    static Attribute SATURATION;
    // virtual void reloadHardcoded(Actor::InitializationMethod, VariantParameterList const&);
    // virtual void reloadHardcodedClient(Actor::InitializationMethod, VariantParameterList const&);
    // virtual void initializeComponents(Actor::InitializationMethod, VariantParameterList const&);
    // virtual void _serverInitItemStackIds();
    // virtual void remove();
    // virtual void move(Vec3 const&);
    // virtual void teleportTo(Vec3 const&, bool, int, int, ActorUniqueID const&);
    // virtual void* getAddPacket();
    // virtual void normalTick();
    // virtual void rideTick();
    // virtual float getRidingHeight();
    // virtual std::__ndk1::string getFormattedNameTag() const;
    // virtual bool getAlwaysShowNameTag() const;
    // virtual float getCameraOffset() const;
    // virtual bool isImmobile() const;
    // virtual bool isSleeping() const;
    // virtual bool isShootable();
    // virtual bool isBlocking() const;
    // virtual bool isDamageBlocked(ActorDamageSource const&) const;
    // virtual bool isCreativeModeAllowed();
    // virtual bool isLocalPlayer() const;
    // virtual bool isPlayer() const;
    // virtual void attack(Actor&);
    // virtual int adjustDamageAmount(int&) const;
    // virtual bool isJumping() const;
    // virtual bool isInvulnerableTo(ActorDamageSource const&) const;
    // virtual void actuallyHurt(int, ActorDamageSource const&, bool);
    // virtual void onBounceStarted(BlockPos const&, Block const&);
    // virtual void feed(int);
    // virtual void handleEntityEvent(ActorEvent, int);
    // virtual int getActorRendererId() const;
    // virtual void awardKillScore(Actor&, int);
    // virtual void setArmor(ArmorSlot, ItemStack const&);
    // virtual ItemStack* getCarriedItem() const;
    // virtual void setCarriedItem(ItemStack const&);
    // virtual void setOffhandSlot(ItemStack const&);
    // virtual ItemStack* getEquippedTotem() const;
    // virtual void consumeTotem();
    // virtual ActorType getEntityTypeId() const;
    // virtual int getPortalCooldown() const;
    // virtual int getPortalWaitTime() const;
    // virtual void onSynchedDataUpdate(int);
    // virtual bool canAddRider(Actor&) const;
    // virtual bool canBePulledIntoVehicle() const;
    // virtual void sendMotionPacketIfNeeded();
    // virtual void startSwimming();
    // virtual void stopSwimming();
    // virtual CommandPermissionLevel getCommandPermissionLevel() const;
    // virtual AnimationComponent* getAnimationComponent() const;
    // virtual void useItem(ItemStackBase&, ItemUseMethod, bool);
    // virtual float getMapDecorationRotation() const;
    // virtual bool isWorldBuilder();
    // virtual bool isCreative() const;
    // virtual bool isAdventure() const;
    // virtual void add(ItemStack&);
    // virtual void drop(ItemStack const&, bool);
    // virtual void setSize(float, float);
    // virtual void startSpinAttack();
    // virtual void stopSpinAttack();
    // virtual void die(ActorDamageSource const&);
    // virtual void* createMovementProxy();
    // virtual void _hurt(ActorDamageSource const&, int, bool, bool);
    // virtual void readAdditionalSaveData(CompoundTag const&, DataLoadHelper&);
    // virtual void addAdditionalSaveData(CompoundTag&);
    // virtual void _onSizeUpdated();
    // virtual void setSleeping(bool);
    // virtual float getSpeed() const;
    // virtual void setSpeed(float);
    // virtual void travel(float, float, float);
    // virtual void aiStep();
    // virtual int getItemUseDuration();
    // virtual float getItemUseStartupProgress();
    // virtual float getItemUseIntervalProgress();
    // virtual void* getAllHand() const;
    // virtual void* getAllEquipment() const;
    // virtual void dropEquipmentOnDeath(ActorDamageSource const&, int);
    // virtual void dropEquipmentOnDeath();
    // virtual void clearVanishEnchantedItemsOnDeath();
    // virtual void sendInventory(bool);
    // virtual bool canExistWhenDisallowMob() const;
    // virtual void* useNewAi() const;
    // virtual void initBodyControl();
    // virtual void jumpFromGround();
    // virtual void updateAi();
    // virtual void updateGliding();
    // virtual void prepareRegion(ChunkSource&);
    // virtual void destroyRegion();
    // virtual void suspendRegion();
    // virtual void resendAllChunks();
    // virtual void _fireWillChangeDimension();
    // virtual void _fireDimensionChanged();
    // virtual void changeDimensionWithCredits(AutomaticID<Dimension, int>);
    // virtual void tickWorld(Tick const&);
    // virtual void getTickingOffsets() const;
    // virtual void moveView();
    // virtual void setName(std::__ndk1::string const&);
    // virtual void checkMovementStats(Vec3 const&);
    // virtual void* getCurrentStructureFeature() const;
    // virtual bool isAutoJumpEnabled() const;
    // virtual void respawn();
    // virtual void resetRot();
    // virtual void resetPos(bool);
    // virtual bool isInTrialMode();
    // virtual bool hasResource(int);
    // virtual void completeUsingTotem();
    // virtual void setPermissions(CommandPermissionLevel);
    // virtual void startDestroying();
    // virtual void stopDestroying();
    // virtual void openPortfolio();
    // virtual void openBook(int, bool, int, BlockActor*);
    // virtual void openTrading(ActorUniqueID const&, bool);
    // virtual bool canOpenContainerScreen();
    // virtual void openChalkboard(ChalkboardBlockActor&, bool);
    // virtual void openNpcInteractScreen(Actor&);
    // virtual void openInventory();
    // virtual void displayChatMessage(std::__ndk1::string const&, std::__ndk1::string const&);
    // virtual void displayClientMessage(std::__ndk1::string const&);
    // virtual void displayTextObjectMessage(TextObjectRoot const&);
    // virtual void displayTextObjectWhisperMessage(ResolvedTextObject const&, std::__ndk1::string const&, std::__ndk1::string const&);
    // virtual void displayWhisperMessage(std::__ndk1::string const&, std::__ndk1::string const, std::__ndk1::string const&, std::__ndk1::string const&);
    // virtual void startSleepInBed(BlockPos const&);
    // virtual void stopSleepInBed(bool, bool);
    // virtual bool canStartSleepInBed();
    // virtual int getSleepTimer() const;
    // virtual int getPreviousTickSleepTimer() const;
    // virtual void openSign(BlockPos const&);
    // virtual void playEmote(std::__ndk1::string const&);
    // virtual bool isHostingPlayer() const;
    // virtual bool isLoading() const;
    // virtual bool isPlayerInitialized() const;;
    // virtual void stopLoading();
    // virtual void registerTrackedBoss(ActorUniqueID);
    // virtual void unRegisterTrackedBoss(ActorUniqueID);
    // virtual void setPlayerGameType(GameType);
    // virtual void _crit(Actor&);
    // virtual void* getEventing() const;
    // virtual void* getUserId() const;
    // virtual void* sendEventPacket(EventPacket&) const;
    // virtual void addExperience(int);
    // virtual void addLevels(int);
    // /*pure*/ virtual void inventoryChanged(Container&, int, ItemStack const&, ItemStack const&, bool);
    // /*pure*/ virtual void deleteContainerManager();
    // virtual void setFieldOfViewModifier(float);
    // virtual bool is2DPositionRelevant(AutomaticID<Dimension, int>, BlockPos const&);
    // virtual bool isEntityRelevant(Actor const&);
    // /*pure*/ virtual void onSuspension();
    // virtual void onLinkedSlotsChanged();
    // virtual void startCooldown(Item const*);
    // virtual int getItemCooldownLeft(std::__ndk1::string const&) const;
    // virtual bool isItemInCooldown(std::__ndk1::string const&) const;
    // /*pure*/ virtual void* sendNetworkPacket(Packet&) const;
    // /*pure*/ virtual void reportMovementTelemetry(MovementEventType);
    // virtual void onMovePlayerPacketNormal(Vec3 const&, Vec2 const&, float);
    void _applyExhaustion(Vec3 const&);
    void setCursorSelectedItemGroup(ItemGroup const&);
    void stopGliding();
    bool isChatAllowed();
    void* getContainerManager();
    void setLastHurtBy(ActorType);
    void _registerPlayerAttributes();
    bool getHasSeenCredits() const;
    void updateCreativeItemList();
    int getLuck();
    void setDefaultHeadHeight();
    void setAgent(Agent*);
    bool forceAllowEating() const;
    int _calculateCritDamage(int&) const;
    void tickArmor();
    void* getClientSubId() const;
    ActorType getLastHurtBy() const;
    bool shouldShowCredits() const;
    bool /*?*/ _validateSpawnPositionAvailability(Vec3 const&, BlockSource*, Vec3 const*) const;
    void queueOnScreenTextureAnimation(unsigned int);
    void setPlayerUIItem(PlayerUISlot, ItemStack const&);
    void _touch(Actor&);
    void* getClientId() const;
    void useMapAnimationComponent(bool);
    bool checkNeedAutoJump(float, float);
    void causeFoodExhaustion(float);
    void _addLevels(int);
    void setSelectedItem(ItemStack const&);
    unsigned int getCurrentOnScreenAnimationEffectID() const;
    bool _validateSpawnIsEmpty(BlockPos);
    bool hasOpenContainerOfContainerType(ContainerType) const;
    void setRespawnReady(Vec3 const&);
    Agent* getAgent() const;
    void _tickCooldowns();
    bool checkSpawnBlock(BlockSource const&) const;
    GameType getPlayerGameType() const;
    Item* getItemInUse() const;
    bool isBouncing() const;
    void broadcastPlayerSpawnedMobEvent(ActorType, MobSpawnMethod);
    void _setBlockedUsingShieldTimeStamp(long long);
    void useUIAnimationComponent(bool);
    void checkBed(BlockSource*, Vec3 const*);
    bool getBlockRespawnUntilClientMessage() const;
    bool canDestroy(Block const&) const;
    ItemStack* getPlayerUIItem(PlayerUISlot);
    bool _shouldAdjustYToSolidGroundOnSpawn(bool, bool, bool, bool, bool);
    int getPlayerLevel() const;
    PlayerInventory* getSupplies() const;
    bool isForcedRespawn() const;
    void moveCape();
    void setBedRespawnPosition(BlockPos const&);
    bool _isChunkSourceLoaded(Vec3 const&, BlockSource const&) const;
    void setEnchantmentSeed(int);
    std::__ndk1::string getInteractText() const;
    int getTicksUsingItem();
    bool canUseOperatorBlocks() const;
    BlockPos* getSpawnPosition() const;
    bool isViewer() const;
    int getScore();
    void onResetBAI(int);
    void clearRespawnPosition();
    // void fireDimensionChangedEvent(AutomaticID<Dimension, int>);
    void _registerElytraLoopSound();
    void clearCreativeItemList();
    Dimension* getSpawnDimension() const;
    long long getBlockedUsingDamagedShieldTimeStamp() const;
    void _findValidPosWithVerticalSpace(BlockPos);
    void updateInventoryTransactions();
    void handleJumpEffects();
    bool isHurt();
    Agent* getAgentIfAllowed(bool, ActorUniqueID) const;
    void* getSelectedItemSlot() const;
    Vec3* getDirection() const;
    bool _isDangerousSpawn(BlockSource&, AABB const&);
    unsigned int getChunkRadius() const;
    int getXpNeededForNextLevel() const;
    bool isEmoting() const;
    void setBlockRespawnUntilClientMessage(bool);
    float getLevelProgress() const;
    BlockPos* getSpawnPositioningTestPosition() const;
    GameType getUnmappedPlayerGameType();
    int getExpectedSpawnDimensionId() const;
    void _blockUsingShield(ActorDamageSource const&, float);
    HudContainerManagerModel* getHudContainerManagerModel();
    void* getFilteredCreativeItemList() const;
    BlockPos* getRespawnAnchorPosition() const;
    ActorUniqueID* getAgentID() const;
    bool isInCreativeMode() const;
    PlayerInventory* getSupplies();
    void useSelectedItem(ItemUseMethod, bool);
    float getDestroyProgress(Block const&) const;
    bool hasRespawnAnchorPosition() const;
    void setHasSeenCredits(bool);
    bool hasRespawnPosition() const;
    void resetOnScreenAnimationTicks();
    void _fixup4JBedSpawnPosition(Vec3&);
    void _chooseSpawnArea();
    bool hasBedPosition() const;
    bool getUsedPotion();
    void _setStartedBlockingTimeStamp(long long);
    bool isSleepingLongEnough() const;
    void* getSleepRotation() const;
    int getMapIndex();
    void setRespawnPositionCandidate();
    bool isHiddenFrom(Mob&) const;
    std::__ndk1::string getRespawnMessage() const;
    void* getCapePos(float);
    void* getCreativeItemList() const;
    void setCursorSelectedItem(ItemStack const&);
    int getAttackDamage();
    void setPlatformOnlineId(std::__ndk1::string const&);
    void setChunkRadius(unsigned int);
    bool _ensureSafeSpawnPosition(Vec3&);
    int getOnScreenAnimationTicks() const;
    int getEnchantmentSeed() const;
    void* getStandingPositionOnBlock(BlockPos const&);
    void _handleCarriedItemInteractText();
    void resetPlayerLevel();
    void _preSpawnBuildSpawnDataCache();
    bool equippedArmorItemCanBeMoved(ItemStack const&) const;
    int getNewEnchantmentSeed();
    void* getPlayerSessionId() const;
    void interact(Actor&, Vec3 const&);
    void* getSkin();
    void setUsedPotion(bool);
    long long getBlockedUsingShieldTimeStamp() const;
    void* getTrackedBosses();
    void setPlatform(BuildPlatform);
    void _sendShieldUpdatePacket(ShieldItem const&, ItemStack const&, ItemStack const&, ContainerID, int);
    void eat(int, float);
    PlayerInventory* getInventory() const;
    void setMapIndex(int);
    bool isHungry() const;
    int getXpNeededForLevelRange(int, int) const;
    float getDestroySpeed(Block const&) const;
    void updateSpawnChunkView();
    CommandPermissionLevel getPlayerPermissionLevel() const;
    bool isSpawned() const;
    BlockPos* getBedPosition() const;
    bool isSurvival() const;
    bool isInRaid() const;
    void updateTrackedBosses();
    void* getPlayerIndex() const;
    void* getSkin() const;
    void setEmotingStatus(bool);
    void dropCursorSelectedItemOnDeath();
    void spawnExperienceOrb(Vec3 const&, int);
    // void setSpawnBlockRespawnPosition(BlockPos const&, AutomaticID<Dimension, int>);
    void startGliding();
    void startUsingItem(ItemStack const&, int);
    std::__ndk1::string getPlatformOnlineId() const;
    bool isRespawningFromTheEnd() const;
    BlockPos* getExpectedSpawnPosition() const;
    // void setRespawnPosition(BlockPos const&, AutomaticID<Dimension, int>, BlockPos const&);
    std::__ndk1::string getItemInteractText(Item const&) const;
    void* getCurrentActiveShield() const;
    void recheckSpawnPosition();
    void removeListener(PlayerListener&);
    void* getItemStackNetManager();
    bool hasOpenContainer() const;
    void updateSkin(SerializedSkin const&, int);
    BuildPlatform getPlatform() const;
    void setAllPlayersSleeping();
    bool canUseAbility(AbilitiesIndex) const;
    bool isUsingItem() const;
    void* getSkinAdjustments() const;
    void stopUsingItem();
    void onMobStatusChanged(ActorUniqueID);
    void addListener(PlayerListener&);
    float _getItemDestroySpeed(Block const&) const;
    // void moveSpawnView(Vec3 const&, AutomaticID<Dimension, int>);
    void setUnderwaterLightLevel(float);
    void eat(ItemStack const&);
    ItemStack* getSelectedItem() const;
    bool hasResource(ItemDescriptor const&);
    bool _shouldCrit(Actor const&) const;
    long long getBlockingStartTimeStamp() const;
    PlayerInventory* getInventory();
    void crackBlock(BlockPos const&, unsigned char);
    bool isSlowedByItemUse() const;
    void releaseUsingItem();
    void _setBlockedUsingDamagedShieldTimeStamp(long long);
    // void setRespawnPosition(BlockPos const&, AutomaticID<Dimension, int>);
    float getUnderwaterLightLevel() const;
    void _updateInteraction();
    void* getCertificate() const;
    bool isOperator() const;
    void* getCursorSelectedItem() const;
    void setPlayerIndex(int);
    void* getItemStackNetManager() const;
    bool hasOwnedChunkSource() const;
    void resetToDefaultGameMode();
    void _chooseSpawnPositionWithinArea();
    bool canBeSeenOnMap() const;
    void take(Actor&, int, int);
    // Added by InnerCore
    float getExhaustion() const;
    // Added by InnerCore
    float getExperience() const;
    // Added by InnerCore
    float getHunger() const;
    // Added by InnerCore
    float getSaturation() const;
    // Added by InnerCore
    float getExpLevel() const;
};


#endif //KEX_PLAYER_HPP